"""Compare deterministic current/fixed matrix drivers on bounded 3c input.

Requires drivers generated by build_io_probe.py. Checks all non-matrix columns
exactly and the fitted diagonal against the independent scalar power output.
This is a correctness run, not a performance benchmark.
"""
import argparse
import datetime
import hashlib
import json
import math
import os
from pathlib import Path
import re
import statistics
import subprocess
import time


def digest(path):
    h = hashlib.sha256()
    with path.open('rb') as stream:
        for chunk in iter(lambda: stream.read(8 * 1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def summary(values):
    if not values:
        return {'count': 0}
    absolute = sorted(abs(v) for v in values)
    pos = .95 * (len(absolute) - 1)
    i = int(pos)
    return dict(count=len(values), median_signed_pct=statistics.median(values),
                median_absolute_pct=statistics.median(absolute),
                p95_absolute_pct=absolute[i] + (pos-i) *
                (absolute[min(i+1, len(absolute)-1)]-absolute[i]),
                max_absolute_pct=absolute[-1])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ('reference', 'corrected', 'hinet', 'catalog', 'output'):
        parser.add_argument(name, type=Path)
    parser.add_argument('--start', default='2005-01-01')
    parser.add_argument('--days', type=int, default=3)
    parser.add_argument('--threads', type=int, default=4)
    args = parser.parse_args()
    if args.days < 1 or args.threads < 1:
        parser.error('days and threads must be positive')
    repo = Path(__file__).resolve().parents[1]
    start = datetime.date.fromisoformat(args.start)
    end = start + datetime.timedelta(days=args.days-1)
    out = args.output.resolve()
    out.mkdir(parents=True, exist_ok=False)
    settings = dict(AUTOFOCUSING_BACKEND='cpu', AUTOFOCUSING_GPU_POWER='off',
                    AUTOFOCUSING_FREQ_MIN='0.1', AUTOFOCUSING_FREQ_MAX='0.25',
                    AUTOFOCUSING_SLOWNESS_MAX='0.165', AUTOFOCUSING_SLOWNESS_STEP='0.005',
                    AUTOFOCUSING_PROFILE='1', OMP_NUM_THREADS=str(args.threads),
                    OMP_DYNAMIC='FALSE')
    env = {k: v for k, v in os.environ.items()
           if not k.startswith(('AUTOFOCUSING_', 'OMP_', 'KMP_'))}
    env.update(settings)
    report = dict(settings=settings, component_mode='3c', start=str(start), end=str(end),
                  fftw='ESTIMATE | UNALIGNED', bootstrap_seed='1837 + 104729 * replicate',
                  performance_claim=False, sources=[], runs=[], checks={})
    def save():
        (out/'report.json').write_text(json.dumps(report, indent=2)+'\n')
    sources = []
    for offset in range(args.days):
        day = start + datetime.timedelta(days=offset)
        source = args.hinet.resolve()/day.strftime('%Y/%m%d/%Y%j0000.h5')
        before = source.stat()
        hashed = digest(source)
        after = source.stat()
        if (before.st_size, before.st_mtime_ns) != (after.st_size, after.st_mtime_ns):
            raise RuntimeError(f'Input is still changing: {source}')
        record = dict(path=str(source), size=after.st_size, mtime_ns=after.st_mtime_ns,
                      sha256=hashed)
        report['sources'].append(record)
        sources.append((source, record))
        link = out/'input'/day.strftime('%Y/%m%d')/source.name
        link.parent.mkdir(parents=True)
        link.symlink_to(source)
    report['catalog_sha256'] = digest(args.catalog.resolve())
    save()
    data = {}
    for label in ('reference', 'corrected'):
        exe = getattr(args, label).resolve()
        info = json.loads(subprocess.check_output([str(exe), '--frequency-info'], env=env, text=True))
        if (info['min_bin'], info['max_bin']) != (102, 256):
            raise RuntimeError('Unexpected FFT band')
        command = [str(exe), str(start.year), 'spectral-matrix-3c', label,
                   str(out/'input'), str(args.catalog.resolve()), str(out/'results'),
                   '3c', str(start), str(end)]
        print(f'Running {label}: {start} through {end}', flush=True)
        began = time.monotonic()
        with (out/f'{label}.log').open('w') as log:
            result = subprocess.run(command, cwd=repo, env=env, stdout=log,
                                    stderr=subprocess.STDOUT, timeout=3600)
        report['runs'].append(dict(label=label, command=command, exit_code=result.returncode,
                                   elapsed_s=time.monotonic()-began, binary_sha256=digest(exe),
                                   frequency_band=info))
        save()
        result.check_returncode()
        event_file, = (out/'results'/'spectral-matrix-3c'/label).glob('*.dat')
        rows = [line.split() for line in event_file.read_text().splitlines()]
        if not rows or any(len(row) != 38 for row in rows):
            raise RuntimeError('No events or unexpected column count')
        lines = (out/f'{label}.log').read_text().splitlines()
        segments = [line for line in lines if line.startswith('#Segment ')]
        choices = [line for line in lines if line.startswith(('#deg max=', '#dp_Δ max='))]
        loads = []
        for line in lines:
            match = re.match(r'^#Read data: load_h5 (\S+) (\d+) ', line)
            if match:
                loads.append(dict(path=match[1], stations=int(match[2])))
        nonfinite = [(i+1, j+1) for i, row in enumerate(rows)
                     for j in range(38) if j not in (0,18) and not math.isfinite(float(row[j]))]
        data[label] = (rows, segments, choices)
        report['runs'][-1].update(events=len(rows), event_sha256=digest(event_file),
                                  loads=loads, segments=segments, nonfinite_cells=nonfinite)
        save()
        print(f'{label}: {len(rows)} events, {len(segments)} segments', flush=True)
    old, segments, choices = data['reference']
    new, new_segments, new_choices = data['corrected']
    checks = report['checks']
    checks['non_matrix_columns_exact'] = [r[:33] for r in old] == [r[:33] for r in new]
    checks['accepted_windows_exact'] = segments == new_segments
    checks['initial_candidates_exact'] = choices == new_choices
    checks['all_requested_days_loaded'] = all(len(r['loads']) == args.days and
                                               all(d['stations'] > 0 for d in r['loads'])
                                               for r in report['runs'])
    checks['all_output_finite'] = all(not r['nonfinite_cells'] for r in report['runs'])
    if len(old) != len(new):
        save()
        raise RuntimeError('Event count changed')
    differences = {str(j+1): [] for j in range(33,38)}
    fitted = {str(c): [] for c in range(3)}
    near_zero = {str(j+1): 0 for j in range(33,38)}
    max_scaled = 0.
    for before, after in zip(old, new):
        if before[:2] != after[:2]:
            raise RuntimeError('Event identities changed')
        component = int(after[1])
        scalar = float(after[32]) / (155/1024)
        diagonal = float(after[33+component])
        scale = max(abs(scalar), abs(diagonal), 1e-30)
        max_scaled = max(max_scaled, abs(diagonal-scalar)/scale)
        if scalar > 0:
            fitted[str(component)].append(100*(float(before[33+component])/scalar-1))
        for j in range(33,38):
            b, a = float(before[j]), float(after[j])
            if abs(a) > 1e-30:
                differences[str(j+1)].append(100*(b-a)/abs(a))
            else:
                near_zero[str(j+1)] += 1
    # Event files use six significant digits, not full binary precision.
    checks['corrected_diagonal_matches_scalar'] = max_scaled < 2e-5
    report['corrected_diagonal_max_scaled_difference'] = max_scaled
    report['matrix_relative_error_pct'] = {k: summary(v) for k,v in differences.items()}
    report['fitted_diagonal_relative_error_pct'] = {k: summary(v) for k,v in fitted.items()}
    report['matrix_near_zero_exclusions'] = near_zero
    checks['input_hashes_unchanged'] = all(digest(p) == r['sha256'] for p,r in sources)
    checks['catalog_hash_unchanged'] = digest(args.catalog.resolve()) == report['catalog_sha256']
    save()
    print(json.dumps(checks, indent=2), flush=True)
    if not all(checks.values()):
        raise RuntimeError('Qualification check failed; inspect report.json')


if __name__ == '__main__':
    main()
